apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  # clusterIP: None # this means we are going to use Pod IP deployment having 1 replica only
