apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-admin-binding
roleRef:
  kind: ClusterRole
  name: cluster-admin       # default cluster admin group
  apiGroup: rbac.authorization.k8s.io/v1
subjects:
  - kind: Group
    name: my-admin
    apiGroup: rbac.authorization.k8s.io/v1