apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata: 
  name: mywebsite
  labels:
    app: mywebsite
spec:
  source:
    type: Git
    git:
      uri: https://github.com/AdminTurnedDevOps/GoWebAPI
    contextDir: .
  strategy: 
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: vishnutheja_api:latest