apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns-production
spec:
  acme:
    email: vishnuthejabhadri@gmail.com
    server: https://acme-v02.letsencrypt.org/directory
    privateKeySecretRef:
      name: dns-production-cluster-issuer
    solvers:
      - selector:
          dnsZones:
            - vishnuthejabhadri.xyz # your DNS name
        dns01:
          route53:
            region: us-east-1
            hostedZoneID: Z096843313V3REMT67ZW # your hostedzone ID from AWS
