apiVersion: cert-manager.io/v1
kind: ClusterIssuer # or Issuer
# cluster issuer once create use in all the namespaces
metadata:
  name: http-production
spec:
  acme:
    email: vishnutheja88@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory # for production
    # staging server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-production-cluster-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: external-nginx #ingress cluster name